// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zjtbuywtkpeoydvcpsns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqdGJ1eXd0a3Blb3lkdmNwc25zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk1Njc1MjQsImV4cCI6MjA1NTE0MzUyNH0.pgDuVWBMpYc9dV_9IoFGhcov0uDFqXgaBo9xKvjE_3M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);